### ISSUE TITLE
Wallpaper link is dead

### ISSUE THREAD

**Issue by JakeStanger** [yavko/Dotfiles#1]
Just thought you should know, since I came across it while building :)

The link to your wallpaper 404s, it looks like the repo doesn't exist anymore.

https://github.com/yavko/Dotfiles/blob/b771bea4eecb6b89892ddce7c64af3a8706b8890/modules/greetd.nix#L10
https://github.com/yavko/Dotfiles/blob/b771bea4eecb6b89892ddce7c64af3a8706b8890/home/gui/wallpaper.nix#L21

**Comment by yavko** [comment]
Yeah it seems catppuccin decided not to provide wallpapers anymore due to legal reasons, I'll replace the link with a file for now

**Comment by yavko** [comment]
Fixed in https://github.com/yavko/Dotfiles/commit/892525329bd229220ee88d4f4d76b0d1c0de797a

**Comment by yavko** [comment]
Started using wallpkgs, and asked author to add this wallpaper to it :)
